import type { ToolWebsite } from '~/types/api'

export default defineEventHandler(async (): Promise<ToolWebsite[]> => {
  return [
    // AI 相关
    {
      id: '1',
      name: 'Claude Cookbooks',
      url: 'https://github.com/anthropics/claude-cookbooks',
      description: 'Anthropic 官方提供的 Claude AI 使用示例和最佳实践集合',
      category: 'AI',
      tags: ['Claude', '教程', '示例代码', 'AI助手'],
      icon: '📚',
      createdAt: '2024-11-01',
    },
    {
      id: '2',
      name: 'Claude Academy',
      url: 'https://academy.claude-code.club/',
      description: 'Claude 编程学院，学习如何更好地使用 Claude 进行开发',
      category: 'Learn',
      tags: ['Claude', '教程', 'AI编程', '学习'],
      icon: '🎓',
      createdAt: '2024-11-05',
    },
    {
      id: '3',
      name: 'Google Stitch',
      url: 'https://stitch.withgoogle.com/',
      description: 'Google 推出的创意工具，用于探索 AI 在设计中的应用',
      category: 'AI',
      tags: ['设计', 'Google', '创意工具'],
      icon: '🧵',
      createdAt: '2024-10-20',
    },

    // Vue 生态
    {
      id: '4',
      name: 'Vue.js',
      url: 'https://cn.vuejs.org/',
      description: '渐进式 JavaScript 框架，易学易用，性能出色',
      category: 'Vue',
      tags: ['框架', 'JavaScript', '前端'],
      icon: '💚',
      createdAt: '2024-10-01',
    },
    {
      id: '5',
      name: 'Nuxt',
      url: 'https://nuxt.com/',
      description: '基于 Vue.js 的直观 Web 框架，支持 SSR、SSG 等多种渲染模式',
      category: 'Vue',
      tags: ['框架', 'SSR', 'Vue', '全栈'],
      icon: '🚀',
      createdAt: '2024-10-15',
    },
    {
      id: '6',
      name: 'Vue Bits',
      url: 'https://vue-bits.dev/backgrounds/ballpit',
      description: 'Vue 组件和效果展示，包含各种酷炫的背景动画效果',
      category: 'Vue',
      tags: ['组件', '动画', '效果', 'Canvas'],
      icon: '✨',
      createdAt: '2024-11-08',
    },
    {
      id: '7',
      name: 'VxeTable',
      url: 'https://vxetable.cn/v4/#/demo/list',
      description: '强大的 Vue 表格组件库，功能丰富、性能卓越',
      category: 'Vue',
      tags: ['表格', '组件库', 'Vue', '数据展示'],
      icon: '📊',
      createdAt: '2024-09-20',
    },

    // UI & CSS 框架
    {
      id: '8',
      name: 'UnoCSS',
      url: 'https://unocss.dev/',
      description: '即时按需的原子化 CSS 引擎，灵活且高性能',
      category: 'UI',
      tags: ['CSS', '原子化', '框架', '工具'],
      icon: '⚡',
      createdAt: '2024-10-10',
    },
    {
      id: '9',
      name: 'Tailwind CSS v4',
      url: 'https://tailwindcss.zhcndoc.com/blog/tailwindcss-v4',
      description: 'Tailwind CSS 第四版，性能更快、功能更强大的实用工具优先 CSS 框架',
      category: 'UI',
      tags: ['CSS', '框架', 'Tailwind', '工具类'],
      icon: '🎨',
      createdAt: '2024-11-12',
    },
    {
      id: '10',
      name: 'Kigen Design Color',
      url: 'https://kigen.design/color',
      description: '色彩设计工具，帮助设计师创建和谐的配色方案',
      category: 'Design',
      tags: ['配色', '设计工具', '色彩', 'UI'],
      icon: '🎨',
      createdAt: '2024-11-10',
    },

    // Design 设计工具
    {
      id: '11',
      name: 'Figma Community',
      url: 'https://www.figma.com/community/make',
      description: 'Figma 社区创作平台，发现和分享设计资源、插件和模板',
      category: 'Design',
      tags: ['设计', '社区', '模板', '插件'],
      icon: '🎯',
      createdAt: '2024-11-01',
    },

    // Canvas & 3D 图形库
    {
      id: '12',
      name: 'Three.js',
      url: 'https://threejs.org/',
      description: '强大的 JavaScript 3D 图形库，轻松创建 WebGL 3D 场景',
      category: '3D',
      tags: ['3D', 'WebGL', '图形', '动画'],
      icon: '🎮',
      createdAt: '2024-09-15',
    },
    {
      id: '13',
      name: 'Fabric.js',
      url: 'https://fabricjs.com/',
      description: '强大而简单的 Canvas 库，用于处理 HTML5 画布元素',
      category: 'Canvas',
      tags: ['Canvas', '图形编辑', 'JavaScript'],
      icon: '🖼️',
      createdAt: '2024-09-25',
    },
    {
      id: '14',
      name: 'Konva.js',
      url: 'https://konvajs.org/',
      description: '2D Canvas JavaScript 框架，支持桌面和移动应用',
      category: 'Canvas',
      tags: ['Canvas', '2D', '图形', '交互'],
      icon: '🎨',
      createdAt: '2024-10-05',
    },

    // Learn 学习资源
    {
      id: '15',
      name: 'SVG Tutorial',
      url: 'https://svg-tutorial.com/',
      description: '完整的 SVG 学习教程，从基础到高级的 SVG 技术',
      category: 'Learn',
      tags: ['SVG', '教程', '图形', '学习'],
      icon: '📐',
      createdAt: '2024-10-20',
    },
    {
      id: '16',
      name: 'PhET 互动仿真',
      url: 'https://phet.colorado.edu/zh_CN/',
      description: '科罗拉多大学提供的免费互动科学和数学仿真教学工具',
      category: 'Learn',
      tags: ['教育', '科学', '数学', '互动'],
      icon: '🔬',
      createdAt: '2024-09-10',
    },
    {
      id: '17',
      name: 'Patterns.dev',
      url: 'https://www.patterns.dev/#patterns',
      description: '现代 Web 应用的设计模式和最佳实践集合，涵盖性能、渲染等主题',
      category: 'Learn',
      tags: ['设计模式', '最佳实践', 'Web开发', '性能优化'],
      icon: '📚',
      createdAt: '2024-11-13',
    },
    {
      id: '18',
      name: 'JavaScript.info',
      url: 'https://zh.javascript.info/',
      description: '现代 JavaScript 教程，从基础到高级，内容全面深入',
      category: 'Learn',
      tags: ['JavaScript', '教程', '编程', '前端'],
      icon: '📖',
      createdAt: '2024-11-13',
    },
    {
      id: '19',
      name: 'Git 教程 - Nulab',
      url: 'https://nulab.com/zh-cn/learn/software-development/git-tutorial/',
      description: 'Nulab 提供的详细 Git 版本控制教程，适合初学者和进阶学习',
      category: 'Learn',
      tags: ['Git', '版本控制', '教程', '开发工具'],
      icon: '🌿',
      createdAt: '2024-11-13',
    },
    {
      id: '20',
      name: 'web.dev',
      url: 'https://web.dev/about?hl=zh-cn',
      description: 'Google 提供的 Web 开发指南，包含最佳实践、性能优化和现代 Web 技术',
      category: 'Learn',
      tags: ['Web开发', 'Google', '最佳实践', '性能'],
      icon: '🌐',
      createdAt: '2024-11-13',
    },
  ]
})
