import type { ToolWebsite } from '~/types/api'

export default defineEventHandler(async (): Promise<ToolWebsite[]> => {
  // Mock 数据
  return [
    {
      id: '1',
      name: 'ChatGPT',
      url: 'https://chat.openai.com',
      description: 'OpenAI 的对话式 AI 助手，可以回答问题、提供建议、帮助编写代码等',
      category: 'AI',
      tags: ['对话', 'GPT', '编程助手'],
      icon: '🤖',
      createdAt: '2024-01-15',
    },
    {
      id: '2',
      name: 'Claude',
      url: 'https://claude.ai',
      description: 'Anthropic 开发的 AI 助手，擅长分析、写作和编程',
      category: 'AI',
      tags: ['对话', '分析', '编程'],
      icon: '🧠',
      createdAt: '2024-02-20',
    },
    {
      id: '3',
      name: 'Midjourney',
      url: 'https://www.midjourney.com',
      description: 'AI 图像生成工具，通过文字描述生成高质量图片',
      category: 'AI',
      tags: ['图像生成', '设计', '艺术'],
      icon: '🎨',
      createdAt: '2024-01-10',
    },
    {
      id: '4',
      name: 'Electron',
      url: 'https://www.electronjs.org',
      description: '使用 Web 技术构建跨平台桌面应用的框架',
      category: 'Electron',
      tags: ['框架', '桌面应用', '跨平台'],
      icon: '⚡',
      createdAt: '2024-03-01',
    },
    {
      id: '5',
      name: 'Electron Builder',
      url: 'https://www.electron.build',
      description: '完整的 Electron 应用打包和发布解决方案',
      category: 'Electron',
      tags: ['打包', '发布', '工具'],
      icon: '📦',
      createdAt: '2024-03-05',
    },
    {
      id: '6',
      name: 'Electron Forge',
      url: 'https://www.electronforge.io',
      description: 'Electron 应用的脚手架和打包工具',
      category: 'Electron',
      tags: ['脚手架', '开发工具'],
      icon: '🔨',
      createdAt: '2024-03-10',
    },
    {
      id: '7',
      name: 'Figma',
      url: 'https://www.figma.com',
      description: '协作式界面设计工具，支持团队实时协作',
      category: 'UI',
      tags: ['设计', '协作', '原型'],
      icon: '🎯',
      createdAt: '2024-02-01',
    },
    {
      id: '8',
      name: 'Dribbble',
      url: 'https://dribbble.com',
      description: '设计师社区和作品展示平台',
      category: 'UI',
      tags: ['设计', '灵感', '社区'],
      icon: '🏀',
      createdAt: '2024-02-05',
    },
    {
      id: '9',
      name: 'Tailwind CSS',
      url: 'https://tailwindcss.com',
      description: '实用优先的 CSS 框架，快速构建现代网站',
      category: 'UI',
      tags: ['CSS', '框架', '样式'],
      icon: '💨',
      createdAt: '2024-02-10',
    },
    {
      id: '10',
      name: 'Shadcn UI',
      url: 'https://ui.shadcn.com',
      description: '基于 Radix UI 和 Tailwind CSS 的组件集合',
      category: 'UI',
      tags: ['组件库', 'React', 'Tailwind'],
      icon: '🎨',
      createdAt: '2024-02-15',
    },
    {
      id: '11',
      name: 'Stable Diffusion',
      url: 'https://stability.ai',
      description: '开源 AI 图像生成模型',
      category: 'AI',
      tags: ['图像生成', '开源', '模型'],
      icon: '🖼️',
      createdAt: '2024-01-20',
    },
    {
      id: '12',
      name: 'Ant Design',
      url: 'https://ant.design',
      description: '企业级 UI 设计语言和 React 组件库',
      category: 'UI',
      tags: ['组件库', 'React', '企业级'],
      icon: '🐜',
      createdAt: '2024-02-25',
    },
  ]
})
